title: "Your Name"
description: "Education & Research"
theme: minima
# Navigation (what shows in the top menu)
header_pages:
  - research.md
  - publications.md
  - teaching.md
  - cv.md
# Optional: add your social links (uncomment and edit)
# minima:
#   social_links:
#     - { platform: github,  user_url: "https://github.com/YOUR-USERNAME" }
#     - { platform: linkedin, user_url: "https://www.linkedin.com/in/YOUR-LINKEDIN" }
#     - { platform: scholar,  user_url: "https://scholar.google.com/citations?user=YOUR-ID" }
